### PR TITLE
Using D3 to generate SVG graphs

### PR DESCRIPTION
**Pull request by Fju**
Hi Ethan,

I thought that the ApexChart was a bit slow especially when it had to re-compute the graph everytime the browser is resized.
My code uses the D3 library to generate SVG markup for the graph. The SVG data stays the same but gets scaled and resized according to the window size.
I would like to hear your thoughts :v:

Cheers!

### CODE REVIEW

**Comment by Booligoosh** [comment]
Hey Florian, thanks so much for this, it's awesome!!!I really appreciate you taking the time to do this.

I've tried out your version, and overall I really like it, only a few issues I noticed:

- When opening a new tab, the overlay shows in the top right corner with nothing in it before you move the cursor into the window. I think the ideal behaviour would be for it to be hidden until the cursor moves into the window.
- I quite liked the vertical dashed line from the old graph that showed while hovering. If this is complicated then don't worry about it, but if it's something which isn't too hard to add in, that would be awesome.
- With the old graph library, a little bit of space was left at the top and bottom of the SVG so the paths don't hit the edges of the window.

Let me know if you don't have the time (or don't want) to do any of that, as I could attempt to (even though I don't have any experience with d3).

Thanks again :D

**Comment by Fju** [comment]
Hi Ethan,

I will take a look at it. Right now, it doesn't seem too complicated.
Also d3 is pretty awesome, you should give it a try :smile:

**Comment by Fju** [comment]
Hey Ethan,
I think I have fixed all of your mentioned issues. Have a look!

**Comment by Booligoosh** [comment]
Awesome!!! Thanks so much for helping out!
I've merged it, I'll upload a new build to the Chrome store this week.

**Comment by Booligoosh** [comment]
Actually just uploaded it, waiting on approval for the new version. Should be out soon.

**Pull request merged**
