### PR TITLE
Add responsiveness

### PR DESCRIPTION
**Pull request by Fju**
I made the chart adapt to the browsers window size. Before the chart would remain in the width and height when it was created.
While I was at it, I also added CSS media queries that scale down the font size when the browser window is small enough. I chose `1100px` and `1500px` as breakpoints.

Cheers!

### CODE REVIEW

**Comment by Booligoosh** [comment]
Hey @Fju, thanks for the PR! Really appreciate it 🎉
Is it possible to submit one pull request just with the chart sizing thing, and a separate one with the CSS changes?

I'll merge the chart sizing one immediately, but I'm still not sure about the font sizes (I think a big font increases the impact) so I might tweak it before merging. It'll also probably give you an extra 2 Hacktoberfest PRs, haha 😄 

Also, it seems like your editor or something changed a lot of the code formatting. Is it possible to exclude that from the new PRs? Just so it's easier to see what's changed in the commit.

However, I know you're doing this on your own time, so it's fine if you don't want to dedicate the time to doing that. Just let me know so I can find some other way of incorporating your changes into the code :)

Once again, thanks for the PR! 🙌

**Comment by Fju** [comment]
Hey Ethan,
thanks for your quick response. I am gonna rework my commit. That formatting thing confused me as well. I honestly don't know why and what inserted the semicolons and stuff. I ran your `lint` and `prettier` scripts over the code, but it didn't change anything.

Anyway, I am going to exclude the media queries or rather move it to a separate PR #hacktoberfest and try to correct the code style.

See you in a bit :smile:

**Comment by Fju** [comment]
I removed all the media queries, so that this PR is only about the chart's resizeability. :v:

**Comment by Booligoosh** [comment]
Awesome, thanks so much!!! 😁 
I merged it, you're now listed on [the website](https://carbon-tab.netlify.com) as a contributor.

**Comment by Fju** [comment]
Glad I could help :v:

**Pull request merged**
